#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

CONFIG_FILE='./tests/phpunit.xml'

if [ ! -d ./docs ]; then
    mkdir ./docs
    chmod 700 docs
fi


if [ -x ./vendor/bin/phpdoc ]; then
    ./vendor/bin/phpdoc run -d ./Shoal -t docs
fi
