<?php
/**
 * \Shoal\Auth\PasswordUtils
 * @author David Cloutman
 * @package \Shoal\Auth
 * @license MIT
 *
 * Provides a mechanism for creating CSRF tokens and nonces.
 * 
 */

namespace Shoal\Auth;

use Shoal\Crypt\Urandom;

class SecurityTokenGenerator {
    const GENERATE_SHA256 = 0;
    const GENERATE_BASE64 = 1;

    protected $sessionNamePrefix = 'shoal';
    protected $cookieNamePrefix = 'shoal';
    protected $useUrandom = false;


    /**
     * Random values are generated by a call to rand() using the maxium allowable range by
     * default. Stronger pseudo-randomness can be achieved by using the /dev/urandom file
     * at the cost of speed due to makeing a call to the filesystem.
     * @param boolean $val true to use /dev/urandom, false to use rand(). Default is false.
     */
    public function setUseUrandom ($val = false) {
        $this->useUrandom = $val;
    }

    public function setNonceCookie () {
        $_COOKIE["{$this->cookieNamePrefix}_nonce"] = $this->generateValue();
    }

    protected function generateValue () {
	$value = -1;

        if ($this->useUrandom) {

        }
        else {
            $value = $this->generateRandomInteger();
        }

	return $value;
    }

    protected function pullBase64String () {
    }

    protected function generateRandomInteger () {
        return rand();
    }

}
